### This is the Terraform-generated stage-build.yml workflow for the timdex-format-stage repository ###
name: Stage Build and Deploy Lambda Container
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Stage Deploy Lambda Container
    uses: mitlibraries/.github/.github/workflows/lambda-shared-deploy-stage.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "timdex-pipeline-lambdas-gha-stage"
      ECR: "timdex-pipeline-lambdas-stage"
      FUNCTION: "timdex-format-stage"
